#set editing-mode vi
alias tst='nunit3-console.exe --agents=8'
alias telnet='/C/Windows/System32/telnet.exe'
alias pass='head -n 1 /g/doc/notes.txt'
alias ext='/C/Program\ Files\ \(x86\)/GitExtensions/GitExtensions.exe'
alias ll='ls -al'
alias np='/C/Program\ Files\ \(x86\)/Notepad++/notepad++.exe'
alias dir='ls'
alias bd='msbuild.exe //t:restore\;build //m //p:Configuration=Debug'
alias br='msbuild.exe //t:restore\;build //m //p:Configuration=Release'
alias msbuild='msbuild.exe //m //t:restore\;build'
alias shit='eval $(thefuck $(fc -ln -1))'
alias FUCK='shit'
alias fuck='shit'
alias SHIT='shit'
alias tfs='git-tf'
alias 7='start https://github.com/embedcard/ecs7 &'
alias 6='start https://github.com/embedcard/ecs6 &'
alias w='start https://helixleisure.atlassian.net/wiki/dashboard.action &'
alias tc='start http://was21:8111/ &'
alias tfs='start http://was21:8080/tfs/_home &'
alias ot='start https://sd.embed.com.au:8888/otrs/index.pl?OTRSAgentInterface=0hs8ZVtpczgLomjk2i9ZLiEdxJrFeaZC &'
alias oc='start http://odeploy.embedcard.com/app#/ &'
alias ez='"G:\tools\Firefox Developer Edition\firefox.exe" https://github.com &'
alias pp='python "F:\Projects\hacker-scripts\GotoPullRequest.py" 6'
alias p='python "F:\Projects\hacker-scripts\GotoPullRequest.py" 7'
alias t='python "F:\Projects\hacker-scripts\GotoTFS.py"'
alias c6='cd /f/projects/ecs6'
alias c7='cd /f/projects/ecs7'
alias ws='python "F:\projects\hacker-scripts\SearchWiki.py"'
alias vim='/g/tools/Vim/vim80/gvim.exe'
alias vi='/g/tools/Vim/vim80/gvim.exe'
alias gfc='python "F:\projects\hacker-scripts\FetchAndCheckoutBranch.py"'
alias gf='python "F:\projects\hacker-scripts\GitFetch.py"'
alias gfa='python "F:\projects\hacker-scripts\GitFetch.py" all'
alias bs='"F:\projects\ecs7\Database\Embed.ECS.DatabaseWizard\BuildWithSchemaChanges.bat";cd /f/projects/ecs7/Database/Embed.ECS.DatabaseWizard'
alias ps=powershell
PROMPT_COMMAND='history -a ~/.bash_history'
